### ISSUE TITLE
How to convert PVector to array

### ISSUE THREAD

**Issue by hganjoo** [JuliaAstroSim/AstroIO.jl#17]
I have an array of PVectors of positions after reading in a GADGET-2 snapshot. I need to filter by the z-coordinate and plot the x and y coordinates of the filtered data. For this, I was looking to convert the array of PVectors into an (n,3) array. 

How can I do this?

**Comment by islent** [comment]
### Option 1: convert the array to `StructArray`, if the data is not too large
```julia
h, d = read_gadget2("test/gassphere_littleendian.gadget2", uAstro);

using StructArrays
pos = StructArray(d.Pos);

pos.x; # access array of x
```

### Option 2: Load position data only and get a `StructArray`
```julia
pos = read_gadget2_pos("test/gassphere_littleendian.gadget2", uAstro);
pos.x; # access array of x
```

### Option 3: `PhysicalParticles.pack_xy` and `PhysicalParticles.pack_xyz`
```julia
using PhysicalParticles
d = rand(PVector{Float64}, 3);
pos = pack_xy(d)
pos[1] # access array of x from Vector of two Vectors

# or

pos = pack_xyz(d)
pos[:,1] # access array of x from Nx3 matrix
# 3D pack is designed for 3d scatter plots, 2D pack is designed for 2D orbit plots

# You can also change packing axes, for example:
pos = pack_xy(d, xaxis=:z, yaxis=:x)
pos[1] # access array of z from Vector of two Vectors
```

### Option 4: write an iterator by hand

### Option 5: analyse and visualize positions with `AstroPlot.jl`

---
Feel free to reopen the issue
